### ISSUE TITLE
json-shell: different types of files

### ISSUE THREAD

**Issue by pfuntner** [pfuntner/toys#121]
It occurred to me that this could be used on:
- yaml files
- XML files??? - This probably involves a revisioning of the parsed document

### XML revisioning
Consider:
```
<tag1 key1="value1" key2="value2">
  <tag2 key3="value3"/>
</tag2>
```

This might be presented as follows in YAML:
```
- tag: tag1
  attrs:
    - key1: value1
    - key2: value2
  children:
    - tag: tag2
      attrs:
        - key3: value3
```

The top list (the root) will never have more than one element.
